### ISSUE TITLE
Exit Status 1

### ISSUE THREAD

**Issue by evansvince** [hashicorp/otto#234]
Raw Vagrant output will begin streaming in below. Otto does
    not create this output. It is mirrored directly from Vagrant
    while the development environment is being created.
    
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 66 of file VBoxManageHostonly.cpp

Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
$ otto dev address
172.16.1.227
$ otto dev ssh
==> Executing SSH. This may take a few seconds...
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine.

Error executing Vagrant: exit status 1

**Comment by chad-thompson** [comment]
This seems to be an issue with your Virtual Box installation:

1)  Do you have the latest (at least 4.x) version of VirtualBox installed?
2)  Can you create a simple Vagrant project directly?

The error here is correct - if there is an issue with the VirtualBox install, `VBoxManage` won't work.

**Comment by evansvince** [comment]
You are correct. VirtualBox needs to be updated first.

**Comment by shoneslab** [comment]
I am having the same issue. My machine is installed with vmware fusionm vagrant-fusion lisense, and virtual box. 'otto dev' commands exits with error.

Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: '/Users/jacobs2/.otto.d/global-data/vagrant-layered/layers/consul/Vagrantfile'. This can take some time...
==> default: Skipping vmnet device verification, verify_vmnet is set to false.
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.173.235:22
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: file...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: [otto] Setting locale to en_US.UTF-8...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: [otto] Updating apt...
==> default: [otto] Installing supporting packages...
==> default: [otto] Installing Ruby 2.2. This can take a few minutes...
==> default: [otto] Installing Bundler...
==> default: [otto] Configuring Git to use SSH instead of HTTP so we can agent-forward private repo auth...
==> default: Attempting graceful shutdown of VM...
==> Creating local development environment with Vagrant if it doesn't exist...
Bringing machine 'default' up with 'virtualbox' provider...
The clone environment hasn't been created yet. To clone from
another Vagrantfile, it must already be created with `vagrant up`.
It doesn't need to be running.

Additionally, the created environment must be started with a provider
matching this provider. For example, if you're using VirtualBox,
the clone environment must also be using VirtualBox.
Error building dev environment: Error executing Vagrant: exit status 1

The error messages from Vagrant are usually very informative.
Please read it carefully and fix any issues it mentions. If
the message isn't clear, please report this to the Otto project.
