### ISSUE TITLE
PHP version customization has no effect

### ISSUE THREAD

**Issue by soupdiver** [hashicorp/otto#238]
I tried a simple `Appfile`
```
application {
  name = "laravel"
  type = "php"
}

customization "php" {
  php_version = "5.5"
}
```
Also tried:
```
customization "php" {
  php_version = "5.7"
}
```

In both cases the result is:
```
vagrant@precise64:/vagrant$ php -v
PHP 5.6.14-1+deb.sury.org~precise+1 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

I started digging in the source code and came to: https://github.com/hashicorp/otto/blob/master/builtin/app/php/customization.go#L13

When I add some debug output at this point, the correct version is loaded.
I also found: https://github.com/hashicorp/otto/blob/master/builtin/app/php/data/common/dev/Vagrantfile.tpl which I think is the template used to provision my dev box.
There it var `{{ php_version }}` is used but I can't find the place where the template is rendered and the earlier loaded data is passed through the template. Can you point me somewhere?

**Comment by leowmjw** [comment]
Current version has no customization for PHP ==> https://ottoproject.io/docs/apps/php/customization.html

At best now, you can use the Docker-external App Type to load a PHP 5.7 container.

I think a port Laravel's Homestead Vagrant setup as a PHP sub-App Type; would be the way to go.

You'll want to participate in giving the Hashicorp folks PHP specific "best practices" for Laravel at:  https://github.com/hashicorp/otto/labels/app%2Fphp

Cheers!
Michael Leow

**Comment by chad-thompson** [comment]
At present, the PHP version is locked to only two versions:

1.  A version of PHP 5.6 (the only one that really 'works' from the ondrej PHP PPA repository.  The Vagrantfile generated by the Otto template has this in the script:
```
sudo add-apt-repository -y ppa:ondrej/php5-{{ php_version }}
```
(The 5.5 install fails miserably due to readline, etc., etc. issues if you're using composer, and the PHP 5.4. version from ondrej uses a different 'archive' format altogether.)

.. and the version of PHP that is in the 12.04 Ubuntu repo (5.3.10).  We would need to do a little work to make this 'go', and I've been tinkering with installing different versions using the bash script in the Vagrantfile template.  (Including "5.7/7.0 and HHVM)

**Comment by chad-thompson** [comment]
I added a pull request that will hopefully address some of these issues:

https://github.com/hashicorp/otto/pull/242

I'll note that while the script is 'kinda there', there are some issues I encountered with support for HHVM and PHP 7.0 (the ondrej package in particular does not support the 'precise' Vagrant box we're all building on top of.)

**Comment by Swader** [comment]
Now that version customization is supported in the latest release, some docs on which versions are supported would be nice. Specifically, HHVM and PHP 7 need to be kept in mind here.

**Comment by chad-thompson** [comment]
Right - there is a dependency on the box as well.  I couldn't find (at least in a short amount of research) a PPA for the current Ubuntu version that supports HHVM and PHP 7.

**Comment by Swader** [comment]
[HHVM](https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-14.04) and [PHP 7](https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0)

**Comment by leowmjw** [comment]
An idea for the group to consider:

Why not use a trimmed down version of @fideloper's Vaprobash  as a base for the PHP app type instead? Of course, pieces not related to PHP should be separated out as application dependencies in other Appfiles (e.g Postgres, MySQL, Redis, Elasticsearch ...).

Case for Vaprobash:
1) It is structured fairly modular (and easy to understand); and tunables can be tied to the Appfile customizations (e.g hhvm, php_versions). Features can be enabled by uncommenting on the relevant line (e.g. easily incorporated into otto compile)
2) It is easily synced with Vaprobash's latest versions; so duplicate effort to maintain a "best practice" PHP environment can be minimized.

My initial minimum modification against Vaprobash --> https://github.com/fideloper/Vaprobash/blob/master/Vagrantfile:
```
leow$ diff ~/OTTO/WORKSPACE/vaprobash/Vaprobash/Vagrantfile ./builtin/app/php/data/common/dev/Vagrantfile.tpl
16c16
< hostname        = "vaprobash.dev"
---
> hostname        = "{{ name }}"
24c24
< server_ip             = "192.168.22.10"
---
> server_ip             = "{{ dev_ip_address }}"
114,115c114,116
<   # Enable agent forwarding over SSH connections
<   config.ssh.forward_agent = true
---
>   # Setup a synced folder from our working directory to /vagrant
>   config.vm.synced_folder '{{ path.working }}', "/vagrant",
>     owner: "vagrant", group: "vagrant"
117,121c118,119
<   # Use NFS for the shared folder
<   config.vm.synced_folder ".", "/vagrant",
<             id: "core",
<             :nfs => true,
<             :mount_options => ['nolock,vers=3,udp,noatime,actimeo=2']
---
>   # Enable SSH agent forwarding so getting private dependencies works
>   config.ssh.forward_agent = true
131,132d128
<     vb.name = "Vaprobash"
< 
186c182,199
<   ####
---
>   ################
>   #  Foundation  #
>   ################
>   # Foundation configuration (if any)
>   {% for dir in foundation_dirs.dev %}
>   dir = "/otto/foundation-{{ forloop.Counter }}"
>   config.vm.synced_folder '{{ dir }}', dir
>   config.vm.provision "shell", inline: "cd #{dir} && bash #{dir}/main.sh"
>   {% endfor %}
> 
>   ###############
>   #  Fragments  #
>   ###############
>   # Load all our fragments here for any dependencies.
>   {% for fragment in dev_fragments %}
>   {{ fragment|read }}
>   {% endfor %}
> 
```

Appfile:
```
application {
    name = "custom-otto-php"
    type = "php"

    dependency {
      # source = "/Users/leow/OTTO/WORKSPACE/otto/examples/ruby",
      source = "/Users/leow/OTTO/WORKSPACE/otto/examples/mongodb"
    }
}
```

Basic operations:
```
custom-otto-php leow$ otto dev vagrant ssh
==> Executing: 'vagrant ssh'
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-66-generic x86_64)
...
vagrant@custom-otto-php:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                      NAMES
7c92980a22f9        mongo:3.0           "/entrypoint.sh mongo"   2 minutes ago       Up 2 minutes        0.0.0.0:27017->27017/tcp   mongodb
vagrant@custom-otto-php:~$ dig mongodb.service.consul

; <<>> DiG 9.9.5-3ubuntu0.5-Ubuntu <<>> mongodb.service.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44313
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;mongodb.service.consul.		IN	A

;; ANSWER SECTION:
mongodb.service.consul.	0	IN	A	10.0.2.15

;; Query time: 709 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 04 17:03:33 UTC 2015
;; MSG SIZE  rcvd: 78

vagrant@custom-otto-php:~$ dig custom-otto-php.service.consul

; <<>> DiG 9.9.5-3ubuntu0.5-Ubuntu <<>> custom-otto-php.service.consul
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61039
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;custom-otto-php.service.consul.	IN	A

;; ANSWER SECTION:
custom-otto-php.service.consul.	0 IN	A	10.0.2.15

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Nov 04 17:03:53 UTC 2015
;; MSG SIZE  rcvd: 94

vagrant@custom-otto-php:~$ cd /vagrant
vagrant@custom-otto-php:/vagrant$ php -S 0.0.0.0:8080
PHP 5.6.14-1+deb.sury.org~trusty+1 Development Server started at Wed Nov  4 17:14:03 2015
Listening on http://0.0.0.0:8080
Document root is /vagrant
Press Ctrl-C to quit.
[Wed Nov  4 17:14:06 2015] 100.127.188.1:62616 [200]: /

```

NOTE: There are weird side effects though; need to use "otto dev ssh" otherwise encounter the error [[ exit status 255 ]]

**Comment by mitchellh** [comment]
Fixed!
