### ISSUE TITLE
Append nanobox.io project in « Otto vs. Other Software » documentation section

### ISSUE THREAD

**Issue by harobed** [hashicorp/otto#334]
I suggest to append  nanobox.io project in « Otto vs. Other Software » documentation section ( https://ottoproject.io/intro/vs/index.html ).

Best regards,
Stephane

**Comment by dheerajbhaskar** [comment]
This is how an nanobox team member chose to differentiate. It would be great to hear from the otto team as well. [Source](https://news.ycombinator.com/item?id=10588350)

We, like otto, see the need for tools like these in today's development climate. While both tools are very similar and accomplish nearly the same thing, the main difference is under the hood:
1. Nanobox embraces Docker and the philosophy of containers. Every component and process of your app is housed inside of an isolated container. The VM only runs the Docker deamon and the Nanobox deamon. In contrast, otto leverages Docker, but is built more to conform to Hashicorp's existing toolset.
2. Extensibility in Nanobox is accomplished through engines, which are inspired by and very similar to Heroku buildpacks. As noted above, engines run inside of isolated containers inside the VM. Otto's extensibility is accomplished through Go plugins that run on the host machine.
3. Nanobox caters to the dev workflow. We'll automatically suspend and save the VM state when it's not in use. Nanobox doesn't require the VM to always be running.

**Comment by mitchellh** [comment]
The biggest difference is that Otto also deploys. Other minor differences are a focus on automatically detecting dependencies in addition to just the application itself, a feature that becomes incredibly powerful in Otto 0.2 as we'll see. Also, dependencies as a first class thing to handle microservices.

In addition to that, I can respond to their points directly.

1.) Otto will use containers for deployment because thats where we believe it makes sense. From our experience with Vagrant, containers in development are hugely beneficial for dependencies and for speed. However, for the actual app under development, the workflows aren't great right now. Otto hides this complexity from you and sets you up with a mutable dev environnment to turn into a container later.

For things that containers don't make sense (highly security sensitive software for example, or apps that can benefit hugely from unikernels), we can use VMs. Otto at its core has no tie directly to any technology. 

2.) We use Go plugins because they're ultimately flexible: you can actually choose to execute your code in a VM or not. Some of our app types actually do execute code in a VM to figure out what is going on. But by being a Go plugin you can do _anything_ you want. 

3.) I don't really understand what this is saying, we can also suspend the VM when its not in use. For some app types we don't require a VM at all. I may just be misunderstanding them here though.

Given that it isn't widely adopted right now I don't see a need to put a first class comparison up on the website at this time. If that changes I can do that. For now, hopefully Google will bring curious folks to this page.

**Comment by dheerajbhaskar** [comment]
Thanks for taking the time to write this.

The decision to put it up on the site or not, I'd defer to you and the other maintainers. What would make sense is to compare otto with not only nanobox but other players in this domain. Well, as you've highlighted, nanobox (and others?) are very new. A first-class comparison with other players should make sense very soon, but not now; we can cross the bridge when we get there.

**Comment by mitchellh** [comment]
Hey Dheeraj,

We do have comparisons to others on the site under the intro section.

Best,
Mitchell

**Comment by dheerajbhaskar** [comment]
Hey Mitchell,

Thanks for getting back to me personally. I did check out the comparisons
before my post. I was only mentioning that otto and nanobox (and other new
players) are more similar than different when viewed alongside the previous
comparisons on the site (like comparisons with docker).

This new (at least to me) trend of otto like tools (otto clones you might
call them) might deserve their own section in the comparisons. As you had
earlier highlighted, nanobox (and possibly other players too) is very new
and do not need a first-class comparison, which I agree with. I only
suggested that it might make sense to have comparisons with otto clones (if
I may use the term). You may choose to do that on a whole segment (say
otto-clones) rather than each tool.

This otto clones segment is new and it makes sense for otto to make this
comparison given that it's the leader (IMO) in this domain.

Have a great day.

Regards,
Dheeraj

On Wed, Dec 2, 2015 at 1:48 AM Mitchell Hashimoto <notifications@github.com>
wrote:

> Hey Dheeraj,
>
> We do have comparisons to others on the site under the intro section.
>
> Best,
> Mitchell
>
> On Tuesday, December 1, 2015, Dheeraj Bhaskar <notifications@github.com>
> wrote:
>
> > Thanks for taking the time to write this.
> >
> > The decision to put it up on the site or not, I'd defer to you and the
> > other maintainers. What would make sense is to compare otto with not only
> > nanobox but other players in this domain. Well, as you've highlighted,
> > nanobox (and others?) are very new. A first-class comparison with other
> > players should make sense very soon, but not now; we can cross the bridge
> > when we get there.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/hashicorp/otto/issues/334#issuecomment-161070974>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/otto/issues/334#issuecomment-161083651>.
>
-- 
--- Disclaimer --- The information in this mail is confidential and is
intended solely for addressee. Access to this mail by anyone else is
unauthorised. Copying or further distribution beyond the original recipient
may be unlawful. Any opinion expressed in this mail is that of sender and
does not necessarily reflect that of OSW Technologies Pvt Ltd.---

**Comment by harobed** [comment]
>  I only suggested that it might make sense to have comparisons with otto clones (if I may use the term). You may choose to do that on a whole segment (say otto-clones) rather than each tool.

+1

**Comment by aallbrig** [comment]
> I only suggested that it might make sense to have comparisons with otto clones (if I may use the term). You may choose to do that on a whole segment (say otto-clones) rather than each tool.

+1
