### ISSUE TITLE
Please consider "app.hcl" instead of "Appfile"

### ISSUE THREAD

**Issue by jimmycuadra** [hashicorp/otto#61]
One unfortunate legacy of Makefiles is that editors need to have knowledge of this special case filename to know what type of syntax and plugins to use. If an editor knows how to deal with HCL files, then it should know how to deal with Otto's appfile without any additional configuration. Please consider using "app.hcl". Ideally this would be the default name, but simply recognizing a file with this name as the appfile would be useful too.

**Comment by st-isidore-de-seville** [comment]
I wholeheartedly agree that this will be an issue for IDEs.

**Comment by chiefy** [comment]
What about `Appfile.hcl` or `Otto.hcl`?

**Comment by AJMiller** [comment]
+1 Appfile.hcl

**Comment by Gurpartap** [comment]
otto compile` accepts an `appfile` flag. See https://github.com/hashicorp/otto/blob/0963ba57d1834574b8a68d0908f90cb4ffaef8ae/command/compile_test.go#L42

This worked for me:
`otto compile -appfile otto.hcl`

**Comment by jimmycuadra** [comment]
While being able to specify a specific appfile is nice, my issue is really a plea not to introduce yet another Foofile into the world.

**Comment by Paulius-Maruska** [comment]
+1 Appfile.hcf

Also, perhaps there could be an order in which otto looks for files?
like:
Appfile
Appfile.hcf
app.hcf
*.hcf (only if there is only 1 .hcf file in current directory)

anyway, just an idea.

**Comment by patrys** [comment]
Please switch to using an extension before the current name becomes widespread.

**Comment by mschuchard** [comment]
As a concrete example, atom already recognizes and formats .hcl and .tf with the language-hcl package.  It would work as is with an app.hcl but would be unfamiliar with appfile.  I am sure this would be an issue for all kinds of other IDEs as the original comment mentions and, although we could use an argument to otto compile, shouldn't the default behavior also be the ideal behavior?

Good analogy with Makefile by the way.  Even today cmake wants editors to recognize it via 'CMakeLists.txt' instead of using a standard extension as .cmake is used for the support modules.

**Comment by thasmo** [comment]
Although some editors allow assigning file names to specific languages I'd love to see a file with extension. (And if possivle lowercase as well.)

**Comment by sethvargo** [comment]
Hey everyone,

I wanted to take a moment to chime in here before the conversation strays too far away and take a moment to explain the reason why we chose "Appfile" :smile:.

One of the reasons we chose the "Appfile" was to provide a familiar feel for users migrating from Vagrant using the "Vagrantfile". It is also very familiar to anyone who has worked with GNU make, Bundler, and a variety of other tools that developers and operators know and love.

I think it's reasonable for us to also detect something like "appfile.hcl", but I doubt we will deprecate "Appfile" in its favor; they can happily co-exist :smile:. A number of other tools (including Make, Bundler, etc) all use `*file`. While I definitely sympathize with the argument that editors do not detect the syntax automatically, I do not think that argument outweighs the importance of having a consistent and delightful experience for users transitioning from Vagrant.

We want the Appfile to be the single source of truth for the way you develop, setup, and deploy applications. The Appfile is part of Otto's branding, and it is deeply engrained in the messaging we've already published and the messaging we plan to publish soon. I do not envision us changing that

This is a great conversation, but I would love to have deeper conversations about the core functionality and help grow the community and support for more builtins. There's so much more to Otto than the name "Appfile", and I think it might be a bit silly to continue debating this instead of focusing on making the core functionality an amazing experience for everyone :wink:.

We will work to add support for both appfile.hcl and Appfile, but I think the otto branding and messaging is going to continue to encourage the use of Appfile :smile:. Thank you to everyone for taking the time to talk about this!

**Comment by jimmycuadra** [comment]
Thanks, Seth, for the thoughtful reply and for considering my request!

The only other thing I want to add is that I think the fact that other tools like Bundler and Vagrant having done this in the past was *also* a mistake, and not a good justification for doing it again. (A related and interesting note, the original creators of Bundler went on to work on the design of [Rust](https://www.rust-lang.org/)'s package manager, Cargo. That past mistake was realized and they chose "Cargo.toml" instead of Cargofile.)

> I do not think that argument outweighs the importance of having a consistent and delightful experience for users transitioning from Vagrant

I'm a long time Vagrant user and carrying this baggage over from Vagrant perpetuates something that was *not* delightful about Vagrant for me.

Again, thanks for the consideration!

**Comment by Skarlso** [comment]
+1 Appfile.hcf. 

I also would like to take a moment to agree with @jimmycuadra. The fact that "others are doing it"  does not make it right. With docker and vagrant it was the same annoyance a file without extension which was, as said, not a delightful experience. 

And of course we are discussing this as well as we are aiming to improve in every aspect, not just the core functionality. Because in the end, it's the little things which topples or uplifts a product.

**Comment by mschuchard** [comment]
> One of the reasons we chose the "Appfile" was to provide a familiar feel for users migrating from Vagrant using the "Vagrantfile". It is also very familiar to anyone who has worked with GNU make, Bundler, and a variety of other tools that developers and operators know and love.

I do not see how a choosing file without an extension makes it familiar.  Having a file with similar syntax or functionality would arguably be something that actually makes it familiar.

**Comment by phinze** [comment]
Hey folks,

@sethvargo did a great job of explaining our thinking on this. For those of your that prefer a different filename - I just added "appfile.hcl" recognition in #146 which will come out with the next Otto release. :+1:

**Comment by Skarlso** [comment]
@phinze +1 for thinking ahead and making it an array. You can earn extra points, if you put it into a CFG of some sort, instead of hardcoding the name of the alternatives. 

In any case, thanks!
