### ISSUE TITLE
Another configuration file format?

### ISSUE THREAD

**Issue by warrenseine** [hashicorp/otto#92]
Hi,

Sorry if this sounds like a first-world problem, but it's better to raise the flag as soon as possible.

Is there a reason for Otto to have yet-another configuration file format? Wouldn't JSON do the job? Or YAML?

There are thousands of reasons why using a standard file format would be preferable (safety, extensibility, readability, "debuggability", third-party usability...). I suppose there was a requirement for Otto to have its own.

Thanks,
Warren.

**Comment by jhedev** [comment]
The format is `HCL` (see [here](https://ottoproject.io/docs/appfile/syntax.html)), which is used for most of the hashicorp tools. 

I guess the `Why?` section of the `HCL` README answers your questions:

https://github.com/hashicorp/hcl#why

**Comment by mitchellh** [comment]
@jhedev nailed it on the head and that section will explain it well for you. 

I do want to say at HashiCorp we've looked for a "standard file format" that fits the bill. I promise we looked at all of them from very old ones such as YAML, to newer ones such as TOML. They all don't strike the balance we're looking for (as explained in "Why?" linked above). 

HCL is a common config format that we're now using in a majority of our tools (and spreading to the rest). Our tools are used by millions of folks and we've gotten great feedback that people enjoy using it.

Best of all, HCL is JSON compatible. You can write the Appfile in JSON if you so please. :) We don't document this because the Appfile is meant for humans to read/write, and we think HCL is the superior format for doing so.

**Comment by warrenseine** [comment]
Great answer. Thank you both for clarifying. I didn't know there was a separate repository for the HCL file format.

When you say it's JSON-compatible, I can easily understand how to translate most of the file format, but how would you convert `customization "go"` (from the [example](https://ottoproject.io/docs/appfile/syntax.html))?

**Comment by jhedev** [comment]
Similar to what is described in the [terraform docs](https://www.terraform.io/docs/configuration/syntax.html), I guess:

```hcl
customization "go" {
    go_version = "1.4.2"
}
```

becomes

```json
"customization": {
  "go": { 
    "go_version": "1.4.2" 
  }
}
```

Confirmed with the getting-started application.

**Comment by hussainweb** [comment]
Thank you for answering the question and it is a relief to see that it's JSON compatible. However, if I needed to write a script to modify an Appfile, it has to first read an existing file. Are there any libraries to read HCL strings and convert them to an array/object. Same question to write output as HCL. If not, is there any effort in that direction?
